### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/skinCareSPA#11]
From John:

```
...The site needs color.  First the header (see diagram).

There is to much blank space on both sides of the product.
We need to make the product boxes bigger.  Probably by 2X.
The name of each product should be listed in the same blue color above each product...
```

[Tweaks.pdf](https://github.com/Kondeo/skinCareSPA/files/153992/Tweaks.pdf)

**Comment by julianpoy** [comment]
For the "Fuzzy images" comment, I believe its simply because of how small it is. He probably does not have an hdpi screen, so that may be what is making it look blurry. Don't worry about that part, but let me know if making the items bigger doesn't fix it.

**Comment by julianpoy** [comment]
Please have this done by Friday 10am if possible. I'd like to get this turned around for him pretty quickly :+1: 
He will have followup tweaks after sending these over, so make sure to leave time in the 2.5hr budget for another issue :)

**Comment by torch2424** [comment]
okay sounds good, this is a very well written issue thank you very much :)

**Comment by julianpoy** [comment]
Absolutely. My pleasure

**Comment by torch2424** [comment]
Found dodger blue tints using http://www.color-hex.com/color/1e90ff

Also in branch designTweaks

**Comment by torch2424** [comment]
Yo! So I did everything he asked for, but I dont know how to clean up thise blurry images. Your JS makes no sense to me

**Comment by julianpoy** [comment]
Yeah, I mentioned above not to worry about it :)
I think it will be fixed on hdpi screens, and with switching the image urls as he provided.
