### ISSUE TITLE
Add Ng-Toast

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/skinCareSPA#6]
Ng-toast should alert a user when they add an item to the cart.

**Comment by julianpoy** [comment]
You said that you would do this quite a while ago. Are you planning on completing this issue?

**Comment by torch2424** [comment]
@julianpoy I can soon! I have been quite busy, and like I said before I feel like you have been back and forth if you wanted me on this, but ow that you have confirmed that you want me to help, I will add this high priority on my to do list

**Comment by julianpoy** [comment]
Excellent.

**Comment by torch2424** [comment]
in branch toasty
